networks:
  chitchat: 
    driver: bridge

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    expose:
      - "5001"
    networks:
      - chitchat

  nginx:
    image: nginx:alpine
    ports:
      - "80:8383"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html 
    depends_on:
      - app
    networks:
      - chitchat